djangoapp/WebSite/urls.py
from django.contrib import admin
from django.urls import path
from WebSite.views import index, aboutClient, contact, booking, service,error404 ,team, testimonial, nossos_servicos
from WebSite import views

app_name = 'WebSite'
urlpatterns = [

    # WebSite:index   WebSite:servicosAdmin .....   url reverse, como buscar
    path('', index, name='index'),
    path('aboutClient/', aboutClient, name='aboutClient'),
    path('error404/', error404, name='404'),
    path('contact/', contact, name='contact'),
    path('booking/', booking, name='booking'),
    path('service/', service, name='service'),
    path('contact/', contact, name='contact'),
    path('team/', team, name='team'),
    path('testimonial/', testimonial, name='testimonial'),
    path('nossos_servicos/', nossos_servicos, name='nossos_servicos'),    


]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('WebSite.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/WebSite/models.py
from django.db import models

# Create your models here.

##Django adiciona o id por padrao
class Services(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=120)
    message = models.TextField(max_length=1000)  
    telephone = models.CharField(max_length=20)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

djangoapp/WebSite/views.py
from email import message
from django.shortcuts import render, redirect
from django.http import HttpResponse
from WebSite.models import Services
from datetime import datetime
from django.shortcuts import render
from django.contrib import messages

from faker import Faker

seedNumber = 10


# Create your views here.
def  index(request):
    return render(
        request,
        'WebSite/index.html'
    )

#Views do site principal clientes
def aboutClient(request):
    return render(
        request,
        'WebSite/about.html'
    )
def booking(request):
    return render(
        request,
        'WebSite/booking.html'
    )
def contact(request):
    return render(
        request,
        'WebSite/contact.html'
    )
def service(request):
    return render(
        request,
        'WebSite/service.html'
    )
def error404(request):
    return render(
        request,
        'WebSite/error404.html'
    )
def service(request):
    return render(
        request,
        'WebSite/service.html'
    )
def team(request):
    return render(
        request,
        'WebSite/team.html'
    )
def testimonial(request):
    return render(
        request,
        'WebSite/testimonial.html'
    )

    






















############VIEW DO SITE TESTE
# View e function da pagina de serevicos
def nossos_servicos(request):
    if request.method == 'GET':  
        # status = request.GET.get('status')
        # print(status)

        # return render(
        #     request,
        #     'WebSite/nossos_servicos.html',
        #     {'STATUS': status} ## Enviando variavel status para o html
        #     )
        return render(
        request,
        'WebSite/nossos_servicos.html',
    )
    elif request.method == 'POST':
        #Variaveis response form post
        type_service = request.POST.get('type_service')
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        telephone = request.POST.get('telephone')
        stat = request.POST.get('status')
        print(stat)
        #Criando uma instancia da model que ira se comunicar com o banco de dados
        service = Services(
            name = name,
            email = email,
            message = message,
            telephone = telephone,
            #date_created = datetime.now(), o DateTimeField(auto_now_add=True)

        )

    #salvar a model em memoria no banco de dados
        service.save()
    return redirect("/nossos_servicos?status=1")


# TODO Rename this here and in `nossos_servicos`
# def formSendDb(request):
    



    #colocando "?" depois do path vc consegue adicionar parametros
    #vc esta adicionando um valor a status que pode ser capturado pelo metodo get, por que vc vai estar renderizando a pag com GET

        # jeito alternativo de pegar o form
    # Dados do formulário
    #   tentar dessa forma dpos
    #     # Dados do formulário
    #     data = {
    #         'tipo-servico': 'manutencao-preventiva',
    #         'name': request.POST.get('name'),
    #         'email': request.POST.get('email'),
    #         'telephone': request.POST.get('telephone'),
    #         'message': request.POST.get('message'),
    #     }

    #     # URL da view
    #     url = '/nossos_servicos'

    #     # Enviar a requisição POST usando requests.post
    #     response = requests.post(url, data=data)

    #     # Verificar se a requisição foi bem-sucedida
    #     if response.status_code == 200:
    #         print('Formulário enviado com sucesso!')
    #     else:
    #         print('Erro ao enviar o formulário:', response.status_code)

    #     return redirect("/nossos_servicos?status=1")


    



# #View func Admin list service
# def servicosAdmin(request):
    
#     if request.method == 'GET':
#         query_params = request.GET    
#         if  query_params.get('fitroDesejado'):
#             name_filter = query_params.get('fitroDesejado')
#             print("filtro")
#             services = Services.objects.filter(name=name_filter)
#         elif query_params.get('Pequisar'):
#             name_search = query_params.get('Pequisar')
#             print("pesquisa")

#             services = Services.objects.filter(name__contains=name_search)
#         else:
#             print("all")

#             services = Services.objects.all()
#         return render(request, 'WebSite/servicosAdmin.html', {'services': services}) # Enviando variável service para html



def filter_by_option(option, value):
    # Função para aplicar filtro com base na opção selecionada
    if option == 'name':
        services = Services.objects.filter(name=value)
    elif option == 'email':
        services = Services.objects.filter(email=value)
    elif option == 'dateSolicited':
        services = Services.objects.filter(date_created=value)
    elif option == 'telephone':
        services = Services.objects.filter(telephone=value)
    else:
        message = "Opção inválida"
        return None, message

    if not services.exists():
        message = "Nenhum resultado encontrado na database"
        return None, message
    message = "Encontrado com sucesso"
    return services, message

def search_by_option(option, value):
    # Função para aplicar pesquisa com base na opção selecionada
    if option == 'name':
        services = Services.objects.filter(name__contains=value)
    elif option == 'email':
        services = Services.objects.filter(email__contains=value)
    elif option == 'dateSolicited':
        services = Services.objects.filter(date_created__contains=value)
    elif option == 'telephone':
        services = Services.objects.filter(telephone__contains=value)
    else:
        message = "Opção inválida"
        return None, message

    if  services.exists():
        message = "Encontrado com sucesso"
        return services, message
    
    message = "Nenhum resultado encontrado na database, se tiver certeza de sua existencia, pode indicar algum erro"
    return None, message
    
def list_all_services(request):
    # Nenhuma opção ou pesquisa, lista todos os serviços
    services = Services.objects.all()
    typeRequisition = "=!=!=!=Listar Todos=!=!=!="
    return render(request, 'WebSite/servicosAdmin.html', {'services': services, 'typeRequisition': typeRequisition})

def servicosAdmin(request):
    if request.method == 'GET':
        query_params = request.GET
        print(query_params)
        if 'filtroDesejado' in query_params:
            # Aplica filtro se 'filtroDesejado' estiver presente
            name_filter = query_params.get('filtroDesejado')
            selected_option = query_params.get('selectedOption')          

            services, message = filter_by_option(selected_option, name_filter)
           
            typeRequisition = "=!=!=!=Filtrar Especifico=!=!=!="
        elif 'Pesquisar' in query_params:
            # Aplica pesquisa se 'Pesquisar' estiver presente
            temp_search = query_params.get('Pesquisar')
            selected_option = query_params.get('selectedOption')
            print(selected_option)
            print("pesquisa")
            services, message = search_by_option(selected_option, temp_search)
            typeRequisition = "=!=!=!=Pesquisar=!=!=!="
        else:
            # Nenhuma opção ou pesquisa, lista todos os serviços
            services = Services.objects.all()
            typeRequisition = "=!=!=!=Listar Todos=!=!=!="
            message = None
        return render(request, 'WebSite/servicosAdmin.html', {'services': services, 'typeRequisition': typeRequisition, 'message': message})
    if request.method == 'POST': ##TODO ARRUMAR ISSO DAQ PQ QUALQUER POST IRA GERAR 1500 USUARIOS NO BANCOD E DADOS
        if seedNumber < 10:
            message = "listando todos"
            seed_services()
        else:
            message = "listando 1500"
            
        services = Services.objects.all()
        typeRequisition = "=!=!=!=Listar Todos=!=!=!="
        return render(request, 'WebSite/servicosAdmin.html', {'services': services, 'typeRequisition': typeRequisition, 'message': message})



def serviceDelete(request, id):
    #TODO arrumar isso que ta tudo bagunçado com gambiarra
    # # SE QUISER ATUALIZAR/MUDAR OS DADOS:
    # service.email = "VcFoiMudado@Paunoseucu.com"
    # service.save()
    service = Services.objects.get(id=id)
    service.delete()
    messages.success(request, 'Serviço excluído com sucesso.')  

    return redirect('/servicosAdmin')
##Utilitarios para desenvovimento e testes


def see_service(request, id):
    service = Services.objects.get(id=id)

    return render(request, 'WebSite/serviceCrudeAdmin.html', {'service': service})






def seed_services(num_entries=1500):
    
    fake = Faker()
    for _ in range(num_entries):
        # Garante que o nome não ultrapasse 50 caracteres
        name = fake.name()[:50]

        # Garante que o e-mail não ultrapasse 150 caracteres
        email = fake.email()[:150]

        # Garante que a mensagem não ultrapasse 1000 caracteres
        message = fake.text(max_nb_chars=1000)

        # Garante que o telefone não ultrapasse 20 caracteres
        telephone = fake.phone_number()[:20]

        date_created = fake.date_time_this_year()
        service = Services(
        name = name,
        email = email,
        message = message,
        telephone = telephone,
        #date_created = datetime.now(), o DateTimeField(auto_now_add=True)

    )
        service.save()

djangoapp/WebSite/WebSite/templates/webantigo/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bem-vindo à Minha Empresa</title>
    <!-- Adicionando Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        header {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1em;
        }

        section {
            padding: 2em;
            text-align: center;
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1em;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>

<body>
    <!-- Barra de navegação Bootstrap -->
    <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
            <h5 class="text-white h4">Oferecimentos Jhoel</h5>
            <span class="text-muted">O que se que ta mole</span>
            <div class="spinner-grow text-success spinner-grow-sm" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-danger spinner-grow-sm" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-warning spinner-grow-sm" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-dark bg-dark ">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="nossos_servicos">Nossos Servicos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="servicosAdmin">Area Admin</a>
                </li>
            </ul>


        </div>

    </nav>





    <header>
        <h1>Bem-vindo à Martins Company</h1>
    </header>

    <section>
        <p>
            Obrigado por visitar nossa página inicial. Somos dedicados a fornecer soluções excepcionais para
            nossos clientes.
        </p>
        <p>
            Explore nosso site para saber mais sobre nossos produtos e serviços.
        </p>
    </section>

    <footer>
        &copy; 2023 Martins Enterprises. Todos os direitos reservados.
    </footer>


    <!-- Colocando notificaçoes -->

    <div aria-live="polite" aria-atomic="true" class="position-relative">
        <!-- Position it: -->
        <!-- - `.toast-container` for spacing between toasts -->
        <!-- - `.position-absolute`, `top-0` & `end-0` to position the toasts in the upper right corner -->
        <!-- - `.p-3` to prevent the toasts from sticking to the edge of the container  -->
        <div class="toast-container position-absolute top-0 end-0 p-3">

            <!-- Then put toasts within -->
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <img  src="https://comicvine.gamespot.com/a/uploads/original/11131/111315773/8883237-8045386711-71834.jpg" class="rounded me-2" alt="..." width="30" height="48">
                    <strong class="me-auto">Charles </strong>
                    <small class="text-muted">Tuo secondings atrix</small>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    !!NOSSA, OLHA OQ APARECEU NO MEU CELULAR!!
                </div>
            </div>

            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <img   src="https://comicvine.gamespot.com/a/uploads/original/11131/111315773/8883237-8045386711-71834.jpg" class="rounded me-2" alt="..." width="30" height="48">
                    <strong class="me-auto">Jhoel Lo Picudo</strong>
                    <small class="text-muted">Bao?</small>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    Se leu é por que me mamou, tmj.
                </div>
            </div>
        </div>
    </div>

<!--Scripts-->


<!-- Adicionando Bootstrap JS (coloque no final do corpo para um carregamento mais rápido) -->
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
<!-- TENTAR USAR O OFFCANVA COM ESSE JAVASCRIPT<script defer src="https://code.jquery.com/jquery-3.6.4.min.js"></script>-->
<!--  inicialização do Offcanvas -->
<script defer>
    document.addEventListener('DOMContentLoaded', function () {
        var offcanvasElementList = [].slice.call(document.querySelectorAll('.offcanvas'))
        var offcanvasList = offcanvasElementList.map(function (offcanvasEl) {
            return new bootstrap.Offcanvas(offcanvasEl)
        })
    });
</script>

 <!-- Script para aguardar 5 segundos e, em seguida, mostrar os toasts -->
 <script>
    // Função para mostrar toasts após 5 segundos
    function mostrarToasts() {
        // Seletor dos toasts
        var toasts = document.querySelectorAll('.toast');

        // Mostrar cada toast individualmente
        toasts.forEach(function (toast, index) {
            // Aguardar 5 segundos antes de mostrar cada toast
            setTimeout(function () {
                var bootstrapToast = new bootstrap.Toast(toast);
                bootstrapToast.show();
            }, 5000 * (index + 1));
        });
    }

    // Chamar a função após 5 segundos
    setTimeout(mostrarToasts, 2000);
</script>


</body>


</html>

djangoapp/WebSite/WebSite/templates/webantigo/nossos_servicos.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Martins Enterprise - Nossos Serviços</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">

        <!-- TODO Mover tanto os Scripts qunato os styles para arquivos separados depois -->
    <style>
        body {
            padding-top: 56px;
        }

        header {
            background-color: #f8f9fa;
            padding: 3rem 0;
        }

        section {
            padding: 3rem 0;
        }

        footer {
            padding: 3rem 0;
            background-color: #343a40;
            color: #ffffff;
        }
        
        /* Estilo para o título (h5) */
        h5 {
            color: rgb(2, 150, 27); 
            font-size: 26px; 
        }

        /* Estilo para o parágrafo (p) */
        p {
            color: #511d83; 
            font-size: 20px; 
        }
    
    </style>
</head>

<body>

    <!-- Barra de Navegação -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Martins Enterprise</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#section-servicos">Serviços</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#section-solicitacao">Solicitar Serviço</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="spinner-grow text-success" role="status">
        <span class="visually-hidden">Waiting..</span>
      </div>
    <!-- Cabeçalho -->
    <header class="text-center mt-5 shadow p-3 mb-5 bg-body rounded ">
        <h1 class="display-4">Martins Enterprise</h1>
        <p class="lead">Serviços Automotivos de Qualidade</p>
    </header>

    <!-- Seção de Serviços -->
    <section id="section-servicos" class="container mt-5">
        <h2 class="h3">Nossos Serviços</h2>

        <!-- Carrossel de Serviços -->
       
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div> 
            <div class="carousel-inner">
              <div class="carousel-item active shadow-sm p-3 mb-5 bg-body rounded" data-bs-interval="10000">
                <img src="https://www.thextremexperience.com/wp-content/uploads/2014/10/Nissan-GT-R-Image-Gallery-1-Xtreme-Xperience-1600x900.jpg" class="d-block w-100 img-fluid rounded" alt="..." max-width="1365" max-height="763">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Qualidade</h5>
                  <p  class="btn btn-outline-info">Potência, desempenho, confiabilidade - porque você merece o melhor.</p>
                </div>
              </div>
              <div class="carousel-item shadow-sm p-3 mb-5 bg-body rounded" data-bs-interval="2000">
                <img src="https://i.pinimg.com/originals/9c/83/36/9c833640c1b47f4a62684b2c0be97760.jpg" class="d-block w-100 img-fluid rounded" alt="..." max-width="1365" max-height="763"> 
                <div class="carousel-caption d-none d-md-block">
                  <h5>Seguraça</h5>
                  <p class="btn btn-outline-info">Onde a qualidade encontra a estrada.</p>
                </div>
              </div>
              <div class="carousel-item shadow-sm p-3 mb-5 bg-body rounded">
                <img src="https://static01.nyt.com/images/2017/04/27/business/28WHEELS-1/28WHEELS-1-superJumbo.jpg" class="d-block w-100 img-fluid rounded" alt="..." max-width="1365" max-height="763">

                <div class="carousel-caption d-none d-md-block">
                  <h5>Confiança</h5>
                  <p class="btn btn-outline-info">Deixe sua marca na estrada com nossa gama de opções de personalização</p>
                </div>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>

        <!-- Descrição dos Serviços -->
        <p  class="shadow-lg p-3 mb-5 bg-body rounded mt-4">Nossa equipe altamente qualificada e apaixonada está pronta para cuidar do seu veículo,
            garantindo durabilidade, desempenho e uma experiência excepcional.</p>
    </section>

    <!-- Seção de Solicitação de Serviços -->
    <section id="section-solicitacao" class="container mt-5">
        <h2 class="h3">Solicitação de Serviços</h2>  
        <!-- IF se a variavel status envida pro html no post de um form service == 1 -->
        {% if STATUS == '1' %}
        <div class="alert alert-success" role="alert">
            Solicitação de Serviço enviada com  <a href="#" class="alert-link">Sucesso</a>
          </div>
        {% endif %}

        <!-- Formulário de Solicitação de Serviços -->
        <form class="form-floating" action="{% url 'WebSite:nossos_servicos' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="tipo-servico" class="form-label">Tipo de serviço</label>
                <select class="form-control" id="tipo-servico" name="tipo-servico">
                    <option value="manutencao-preventiva">Manutenção preventiva</option>
                    <option value="manutencao-corretiva">Manutenção corretiva</option>
                    <option value="outros">Outros</option>
                </select>
            </div>

            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" id="namePerson" name="name" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">E-mail</label>
                <input type="email" class="form-control" id="emailPerson" name="email" required>
            </div>
            <div class="mb-3">
                <label for="telefone" class="form-label">Telefone</label>
                <input type="tel" class="form-control" id="telefonePerson" name="telephone" required>
            </div>
            <div class="mb-3">
                <label for="mensagem" class="form-label">Mensagem</label>
                <textarea class="form-control" id="messagePerson" name="message" rows="4" required></textarea>
            </div>
            <button type="submit" class="btn btn-dark">Enviar Solicitação</button>
        </form>
    </section>

    <!-- Rodapé -->
    <footer class="text-muted text-center mt-5">
        <p>&copy; 2023 Martins Enterprise. Todos os direitos reservados.</p>
    </footer>

    <!-- JavaScript do Bootstrap (coloque no final do corpo para um carregamento mais rápido) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>

djangoapp/WebSite/WebSite/templates/webantigo/serviceCrudeAdmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Editar Serviço</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <h2 class="mb-4">Editar Serviço</h2>
    <form  method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nome" class="form-label">Nome do Serviço:</label>
            <input type="text" class="form-control" id="nome" name="nome" value="{{ service.name }}" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email do Serviço:</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ service.email }}" required>
        </div>
        <div class="mb-3">
            <label for="telefone" class="form-label">Telefone do Serviço:</label>
            <input type="tel" class="form-control" id="telefone" name="telefone" value="{{ service.telephone }}" required>
        </div>
        <div class="mb-3">
            <label for="mensagem" class="form-label">Mensagem do Serviço:</label>
            <textarea class="form-control" id="mensagem" name="mensagem" rows="3" required>{{ service.message }}</textarea>
        </div>
       
        <a href="/serviceDelete/{{ service.id }}" class="btn btn-danger">Exluir</a>
        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
    </form>
</div>

<!-- Bootstrap JS e Popper.js (opcional, se necessário para alguns componentes do Bootstrap) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>